--
-- Script was generated by Devart dbForge Studio for SQL Server, Version 6.5.140.0
-- Product home page: http://www.devart.com/dbforge/sql/studio
-- Script date 27/03/2024 11:56:49
-- Server version: 15.00.4153
--


SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS, XACT_ABORT OFF
GO

USE GestComercial
GO

IF DB_NAME() <> N'GestComercial' SET NOEXEC ON
GO

--
-- Create table [dbo].[Produto]
--
PRINT (N'Create table [dbo].[Produto]')
GO
CREATE TABLE dbo.Produto (
  id int IDENTITY,
  descricao varchar(100) NOT NULL,
  preco decimal(12, 2) NULL,
  PRIMARY KEY CLUSTERED (id)
)
ON [PRIMARY]
GO

--
-- Create table [dbo].[Pais]
--
PRINT (N'Create table [dbo].[Pais]')
GO
CREATE TABLE dbo.Pais (
  nome varchar(100) NOT NULL,
  PRIMARY KEY CLUSTERED (nome)
)
ON [PRIMARY]
GO

--
-- Create table [dbo].[Cliente]
--
PRINT (N'Create table [dbo].[Cliente]')
GO
CREATE TABLE dbo.Cliente (
  id int IDENTITY,
  nome varchar(50) NOT NULL,
  morada varchar(250) NULL,
  estado bit NULL,
  PRIMARY KEY CLUSTERED (id)
)
ON [PRIMARY]
GO

--
-- Create table [dbo].[Venda]
--
PRINT (N'Create table [dbo].[Venda]')
GO
CREATE TABLE dbo.Venda (
  prod int NOT NULL,
  cli int NOT NULL,
  data_venda datetime NOT NULL,
  qtd int NULL,
  PRIMARY KEY CLUSTERED (prod, cli, data_venda)
)
ON [PRIMARY]
GO

-- 
-- Dumping data for table Venda
--
PRINT (N'Dumping data for table Venda')
INSERT dbo.Venda VALUES (1, 1, '2012-04-05 00:00:00.000', 1)
INSERT dbo.Venda VALUES (1, 2, '2012-05-05 00:00:00.000', 5)
GO

-- 
-- Dumping data for table Produto
--
PRINT (N'Dumping data for table Produto')
SET IDENTITY_INSERT dbo.Produto ON
GO
INSERT dbo.Produto(id, descricao, preco) VALUES (1, 'Rato Logitech', 10.00)
INSERT dbo.Produto(id, descricao, preco) VALUES (2, 'Monitor Sony', 120.00)
GO
SET IDENTITY_INSERT dbo.Produto OFF
GO

-- 
-- Dumping data for table Pais
--
PRINT (N'Dumping data for table Pais')
INSERT dbo.Pais VALUES ('Brasil')
INSERT dbo.Pais VALUES ('Espanha')
INSERT dbo.Pais VALUES ('Peru')
INSERT dbo.Pais VALUES ('Portugal')
GO

-- 
-- Dumping data for table Cliente
--
PRINT (N'Dumping data for table Cliente')
SET IDENTITY_INSERT dbo.Cliente ON
GO
INSERT dbo.Cliente(id, nome, morada, estado) VALUES (1, 'Helena Monteiro', 'Perafita', CONVERT(bit, 'True'))
INSERT dbo.Cliente(id, nome, morada, estado) VALUES (2, 'Raul Simas', 'Palmela', CONVERT(bit, 'False'))
GO
SET IDENTITY_INSERT dbo.Cliente OFF
GO

USE GestComercial
GO

IF DB_NAME() <> N'GestComercial' SET NOEXEC ON
GO

--
-- Create foreign key on table [dbo].[Venda]
--
PRINT (N'Create foreign key on table [dbo].[Venda]')
GO
ALTER TABLE dbo.Venda
  ADD FOREIGN KEY (cli) REFERENCES dbo.Cliente (id)
GO

--
-- Create foreign key on table [dbo].[Venda]
--
PRINT (N'Create foreign key on table [dbo].[Venda]')
GO
ALTER TABLE dbo.Venda
  ADD FOREIGN KEY (prod) REFERENCES dbo.Produto (id)
GO
SET NOEXEC OFF
GO