--
-- Script was generated by Devart dbForge Studio for SQL Server, Version 6.5.140.0
-- Product home page: http://www.devart.com/dbforge/sql/studio
-- Script date 27/03/2024 23:06:21
-- Server version: 15.00.4153
--


SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS, XACT_ABORT OFF
GO

USE Encomendas
GO

IF DB_NAME() <> N'Encomendas' SET NOEXEC ON
GO

--
-- Create table [dbo].[Produto]
--
PRINT (N'Create table [dbo].[Produto]')
GO
CREATE TABLE dbo.Produto (
  codProduto int IDENTITY,
  nome varchar(50) NOT NULL,
  preco decimal(12, 2) NULL,
  obs varchar(250) NULL,
  PRIMARY KEY CLUSTERED (codProduto)
)
ON [PRIMARY]
GO

--
-- Create table [dbo].[Cliente]
--
PRINT (N'Create table [dbo].[Cliente]')
GO
CREATE TABLE dbo.Cliente (
  codCliente int IDENTITY,
  nome varchar(50) NOT NULL,
  morada varchar(100) NULL,
  telef int NULL,
  PRIMARY KEY CLUSTERED (codCliente)
)
ON [PRIMARY]
GO

--
-- Create table [dbo].[LinhaEncomenda]
--
PRINT (N'Create table [dbo].[LinhaEncomenda]')
GO
CREATE TABLE dbo.LinhaEncomenda (
  codEncomenda int NOT NULL,
  codProduto int NOT NULL,
  quantidade int NOT NULL,
  desconto int NULL DEFAULT (0),
  CONSTRAINT PK_LINHAENCOMENDA PRIMARY KEY CLUSTERED (codEncomenda, codProduto)
)
ON [PRIMARY]
GO

--
-- Create table [dbo].[Encomenda]
--
PRINT (N'Create table [dbo].[Encomenda]')
GO
CREATE TABLE dbo.Encomenda (
  codEncomenda int IDENTITY,
  codCliente int NOT NULL,
  data datetime NOT NULL,
  PRIMARY KEY CLUSTERED (codEncomenda)
)
ON [PRIMARY]
GO

-- 
-- Dumping data for table Produto
--
PRINT (N'Dumping data for table Produto')
SET IDENTITY_INSERT dbo.Produto ON
GO
INSERT dbo.Produto(codProduto, nome, preco, obs) VALUES (1, 'Rato', 3.00, NULL)
INSERT dbo.Produto(codProduto, nome, preco, obs) VALUES (2, 'Teclado', 12.00, NULL)
INSERT dbo.Produto(codProduto, nome, preco, obs) VALUES (3, 'Monitor', 84.00, NULL)
GO
SET IDENTITY_INSERT dbo.Produto OFF
GO

-- 
-- Dumping data for table LinhaEncomenda
--
PRINT (N'Dumping data for table LinhaEncomenda')
INSERT dbo.LinhaEncomenda VALUES (14, 1, 4, 20)
INSERT dbo.LinhaEncomenda VALUES (15, 2, 2, NULL)
INSERT dbo.LinhaEncomenda VALUES (16, 3, 1, NULL)
GO

-- 
-- Dumping data for table Encomenda
--
PRINT (N'Dumping data for table Encomenda')
SET IDENTITY_INSERT dbo.Encomenda ON
GO
INSERT dbo.Encomenda(codEncomenda, codCliente, data) VALUES (14, 1, '2023-08-09 00:00:00.000')
INSERT dbo.Encomenda(codEncomenda, codCliente, data) VALUES (15, 3, '2024-03-15 00:00:00.000')
INSERT dbo.Encomenda(codEncomenda, codCliente, data) VALUES (16, 3, '2024-01-23 00:00:00.000')
GO
SET IDENTITY_INSERT dbo.Encomenda OFF
GO

-- 
-- Dumping data for table Cliente
--
PRINT (N'Dumping data for table Cliente')
SET IDENTITY_INSERT dbo.Cliente ON
GO
INSERT dbo.Cliente(codCliente, nome, morada, telef) VALUES (1, 'Valéria Romeu', 'Braga', 919191919)
INSERT dbo.Cliente(codCliente, nome, morada, telef) VALUES (2, 'Carlos Rodrigues', 'Porto', 918765432)
INSERT dbo.Cliente(codCliente, nome, morada, telef) VALUES (3, 'Bruno Oliveira', 'Lisboa', 912345678)
INSERT dbo.Cliente(codCliente, nome, morada, telef) VALUES (4, 'Vitor Pacheco', 'Porto', 965432109)
INSERT dbo.Cliente(codCliente, nome, morada, telef) VALUES (6, 'Antonio Moreira', 'Porto', 911222333)
GO
SET IDENTITY_INSERT dbo.Cliente OFF
GO

USE Encomendas
GO

IF DB_NAME() <> N'Encomendas' SET NOEXEC ON
GO

--
-- Create foreign key on table [dbo].[Encomenda]
--
PRINT (N'Create foreign key on table [dbo].[Encomenda]')
GO
ALTER TABLE dbo.Encomenda
  ADD FOREIGN KEY (codCliente) REFERENCES dbo.Cliente (codCliente)
GO

--
-- Create foreign key on table [dbo].[LinhaEncomenda]
--
PRINT (N'Create foreign key on table [dbo].[LinhaEncomenda]')
GO
ALTER TABLE dbo.LinhaEncomenda
  ADD FOREIGN KEY (codEncomenda) REFERENCES dbo.Encomenda (codEncomenda)
GO

--
-- Create foreign key on table [dbo].[LinhaEncomenda]
--
PRINT (N'Create foreign key on table [dbo].[LinhaEncomenda]')
GO
ALTER TABLE dbo.LinhaEncomenda
  ADD FOREIGN KEY (codProduto) REFERENCES dbo.Produto (codProduto)
GO
SET NOEXEC OFF
GO